---
# tasks file for kibana-role
- name: Upload tar.gz Kibana from remote URL
  ansible.builtin.get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    mode: 0755
    timeout: 60
    force: true
    validate_certs: false
  register: get_kibana
  until: get_kibana is succeeded
  tags: kibana
- name: Create directrory for Kibana
  ansible.builtin.file:
    state: directory
    path: "{{ kibana_home }}"
    mode: 0755
  tags: kibana
- name: Extract Kibana in the installation directory
  ansible.builtin.unarchive:
    copy: false
    src: "/tmp/kibana-{{ kibana_version }}-linux-x86_64.tar.gz"
    dest: "{{ kibana_home }}"
    extra_opts: [--strip-components=1]
    creates: "{{ kibana_home }}/bin/kibana"
  tags:
    - kibana
- name: Set environment Kibana
  ansible.builtin.template:
    src: templates/kib.sh.j2
    dest: /etc/profile.d/kib.sh
    mode: 0755
  tags: kibana
